"""empty message

Revision ID: 14b63fcbe017
Revises: b77ad5509860
Create Date: 2025-03-28 13:35:52.598953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b63fcbe017'
down_revision: Union[str, None] = 'b77ad5509860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('association', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('season', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('season', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('association', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
