"""empty message

Revision ID: 4f2a7dbc8330
Revises: a0e215554000
Create Date: 2025-04-01 17:56:18.504771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4f2a7dbc8330'
down_revision: Union[str, None] = 'a0e215554000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_count',
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('division_id', sa.Uuid(), nullable=False),
    sa.Column('age_group_id', sa.Uuid(), nullable=False),
    sa.Column('gender', sa.Integer(), nullable=False),
    sa.Column('association_id', sa.Uuid(), nullable=False),
    sa.Column('team_cnt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['age_group_id'], ['age_group.id'], ),
    sa.ForeignKeyConstraint(['association_id'], ['association.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('season_id', 'division_id', 'age_group_id', 'gender', 'association_id')
    )
    op.add_column('game', sa.Column('gender', sa.Integer(), nullable=False))
    op.drop_column('game', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('id', mysql.CHAR(length=32), nullable=False))
    op.drop_column('game', 'gender')
    op.drop_table('team_count')
    # ### end Alembic commands ###
