"""empty message

Revision ID: 78fd9eda1e96
Revises: b733b39e3645
Create Date: 2025-03-28 11:45:56.065189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '78fd9eda1e96'
down_revision: Union[str, None] = 'b733b39e3645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_group',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_length', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('associationgameinformation',
    sa.Column('association_id', sa.Uuid(), nullable=False),
    sa.Column('age_group_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('slot_length', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['age_group_id'], ['age_group.id'], ),
    sa.ForeignKeyConstraint(['association_id'], ['association.id'], ),
    sa.PrimaryKeyConstraint('association_id', 'age_group_id')
    )
    op.add_column('season', sa.Column('holiday_dates', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('season', 'holiday_dates')
    op.drop_table('associationgameinformation')
    op.drop_table('age_group')
    # ### end Alembic commands ###
