"""empty message

Revision ID: a0e215554000
Revises: 90d3aefbcb4f
Create Date: 2025-03-28 16:01:16.767634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a0e215554000'
down_revision: Union[str, None] = '90d3aefbcb4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('season_id', sa.Uuid(), nullable=False),
    sa.Column('division_id', sa.Uuid(), nullable=False),
    sa.Column('age_group_id', sa.Uuid(), nullable=False),
    sa.Column('home_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('away_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_venue_id', sa.Uuid(), nullable=True),
    sa.Column('game_dt', sa.DateTime(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['age_group_id'], ['age_group.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['sub_venue_id'], ['sub_venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game_schedule')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_schedule',
    sa.Column('season_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('division_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('age_group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('home_team', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('away_team', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sub_venue_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('game_dt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('home_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['age_group_id'], ['age_group.id'], name='game_schedule_age_group_id_fkey'),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], name='game_schedule_division_id_fkey'),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], name='game_schedule_season_id_fkey'),
    sa.ForeignKeyConstraint(['sub_venue_id'], ['sub_venue.id'], name='game_schedule_sub_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='game_schedule_pkey')
    )
    op.drop_table('game')
    # ### end Alembic commands ###
