"""empty message

Revision ID: b77ad5509860
Revises: 78fd9eda1e96
Create Date: 2025-03-28 11:47:35.733521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77ad5509860'
down_revision: Union[str, None] = '78fd9eda1e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('season_length', sa.Integer(), nullable=False))
    op.drop_column('season', 'end_dt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season', sa.Column('end_dt', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('season', 'season_length')
    # ### end Alembic commands ###
