"""add auth0 role table

Revision ID: d5a83b7571ca
Revises: 95dc248d912f
Create Date: 2025-05-12 21:26:42.014398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd5a83b7571ca'
down_revision: Union[str, None] = '95dc248d912f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth0_role',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('sub_venue', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('venue', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('sub_venue', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_table('auth0_role')
    # ### end Alembic commands ###
