"""empty message

Revision ID: ed96d5c741d4
Revises: 4f2a7dbc8330
Create Date: 2025-04-01 19:47:12.212430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ed96d5c741d4'
down_revision: Union[str, None] = '4f2a7dbc8330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_count')
    op.add_column('game', sa.Column('gender_boy', sa.Boolean(), nullable=False))
    op.drop_column('game', 'gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('gender', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('game', 'gender_boy')

    # ### end Alembic commands ###
