name: Build CYSL Website

on:
  push:
    paths:
      - '**'
      - '!README.md'
      - '!VERSION'
    branches:
      - '**'
      - '!releases/**'

defaults:
  run:
    working-directory: src

jobs:    
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v4.1.4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5.1.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/requirements.txt

    - name: Test with pytest
      run: |
        coverage run -m pytest --junitxml=coverage.xml || true
        coverage xml

    - name: Generate reports and fix code coverage paths for Sonarcloud
      run: |
        coverage xml -o coverage.xml
        sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
